### ISSUE TITLE
Can't manage to add release version to plugin name during make release 

### ISSUE THREAD

**Issue by NounouDev** [metwork-framework/mfplugin#19]
The idea is to retrieve release version from **.metadata.json** file. While this is not possible, because the current implementation looks for this json file in **~/metwork/mfmodule/var/plugins** when plugin is not installed. 
The thing is, during **make release** the release version is always fixed to 1:
 https://github.com/metwork-framework/mfplugin/blob/eab633a8d95d8bc08f77709b9118b6af94d8a862/mfplugin/plugin.py#L210
So, the problem is, when the plugin is not installed, the file can't exist in **~/metwork/mfmodule/var/plugins**, and what we want is to look up for this file in the current dir where the make release is executed, so that we can extract the release version and concatenate it at the end of released plugin. 

Other solution that could be intersting is to read the release version from an environment variable.

**Comment by thebaptiste** [comment]
release as been added in mfplugin configuration file (`config.ini` file)
It will possible to manage release exactly as version by changing its value in plugin's `config.ini` file

**Comment by matthieumarrast** [comment]
thank you @thebaptiste, tested OK with image `metwork/mfservplugins-centos8-buildimage:master` (sha256:aaec2705326adbba8b33b6f117ab95604799153a28d72223d6d492f2b61ccf08)
